name: ContSym CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: 🔍 Lint (Flake8 & Pylint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flake8
        run: flake8 src --show-source --statistics --config=.flake8

      - name: Run Pylint
        run: pylint --rcfile=.pylintrc src

  format:
    name: 🎨 Formatting (Black)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Formatting with Black
        run: black --check --diff src

  analyzer_test:
    name: Sanity testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python PKGs and local module
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Running a minimal CLI for analyzer tool
        run: python3 src/cont_sys_sim/container_analyzer/analyzer.py --all-entities --time-window 1 --write-to-file

  uml_generation:
    name: Generate UMLs
    runs-on: ubuntu-latest
    env:
      CONT_ANALYZER: src/cont_sys_sim/container_analyzer
      CONT_SYM: src/cont_sys_sim
      CLI_ANALYZER: src/cont_sys_sim/cli

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz graphviz-dev libgd-dev

      - name: Install Python PKGs and local module
        run: |
          pip install --upgrade pip && pip install -r requirements.txt .

      - name: Generate UMLs
        run: |
          pyreverse --filter-mode=ALL --colorized --output-directory $CONT_ANALYZER -o png -p ContAnalyzer $CONT_ANALYZER
          pyreverse --filter-mode=ALL --colorized --output-directory $CONT_SYM -o png -p ContSym $CONT_SYM
          pyreverse --filter-mode=ALL --colorized --output-directory $CLI_ANALYZER -o png -p CliTool $CLI_ANALYZER

      - name: Upload UML Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UMLs
          path: |
            ${{ env.CONT_ANALYZER }}/*ContAnalyzer*.png
            ${{ env.CONT_SYM }}/*ContSym*.png
            ${{ env.CLI_ANALYZER }}/*CliTool*.png
          retention-days: 1
  release:
    name: 📦 Publish to PyPI
    runs-on: ubuntu-latest
    needs: [lint, format, analyzer_test, uml_generation]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build Distribution
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
